### ISSUE TITLE
前端换成MIT协议？

### ISSUE THREAD

**Issue by meimosor** [ldystudio/next-digital-campus_client#3]
大佬，前端UI这部分MPL协议很少见哦，可以换成宽松点的协议吧，建议换成MIT或者BSD？

**Comment by ldystudio** [comment]
MPL 2.0许可证提供了广泛的灵活性，允许使用、修改和分发代码，同时保留了一定的条款以确保开源社区的良好运作。这个选择是经过深思熟虑的，并与我对项目的愿景和目标保持一致。

我理解不同的项目可能需要不同的许可证，但在当前情况下，我认为MPL 2.0最好地满足了我的项目的需求。再次感谢您的关心和建议，希望您能够理解我的决定。
